name: financial_tracker
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1

  # Local Storage (NoSQL)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utilities
  intl: ^0.19.0
  path_provider: ^2.1.2
  
  # UI & Visuals
  fl_chart: ^0.66.2
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6

  # Platform Specific
  local_auth: ^2.1.8
  csv: ^6.0.0
  share_plus: ^10.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  # Code Generation
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true
